engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 350
        php:
          mass_threshold: 350
    exclude_paths:
      - '**/tests'
  eslint:
    enabled: true
    channel: eslint-2
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: 'php,inc,lib'
      standard: Drupal
      ignore_warnings: true
      encoding: utf-8
ratings:
  paths:
    - '**.inc'
    - '**.module'
    - '**.php'
    - '**.css'
    - '**.inc'
    - '**.js'
    - '**.jsx'
    - '**.es6'
    - '**.module'
exclude_paths:
  - '**/bin'
  - '**/test'
  - '**/tests'
  - '**/tmp'
  - '**/vendor'
  - '**/.idea'
  - '**.spec.js'
  - '**.min.js'
  - '**admin.js'
  - '**.min.css'
  - '**admin.css'
  - '**/dist'
  - '**/node_modules'
  - '**/packages'
