language: php
sudo: required
node_js:
  - 7
cache:
  edge: true
  directories:
    - $HOME/.composer/cache
    - $(npm root -g)
    - node_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - sudo rm -rf ~/.nvm
  - 'curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -'
  - sudo apt-get install -y nodejs
  - cp bin/test/package.json .
after_success:
  - npm run coverage
after_script:
  - npm run remove-coverage
dist: trusty
group: edge
php:
  - 5.6
  - 7.1
install:
  - composer install
  - npm install
script:
  - composer test
  - npm test
env:
  global:
    - NODE_RELEASE=7.x
    - 'MAJOR_VERSIONS=master,stage'
    - E2E_TESTING=none
    - secure: 
        NIHVj4RBAHpPyLFXfZX6Cvo0xhF8b2cXEY10P/++w0Zc4P2QPX3i6jMCoP87beIBKerawB3hfb+6tM7/23eNjfYCkW3IBEnpSo3KhyZYSRM8JUmkOMB589/MeNfJQqLAJlUZ/NP/91yzRcNxOBB0dMBj5bU0XklmKBxEt9jeAhbq67HHI4pq653ms4fzOW0P4tRQcASKgRCB2zO4Vr5fBPHHmXdgd7KI/pEs1v1JhZbIAoiT3aoMzD4j8z5gKlCYASvsT2omT5kauxCGToYFb0nKZVsYsdchZvMWvLcry1ttfYIXsF0jrKnoqcWfSTShTppuudaq3Mx3hzYhUgeXGPlD1/+DXdtv23Vs68+QuBtqjfCgXVRKhvVVX4p8NprtFkU00tRrglktwnBf9j9k74SNKsrMeRNx8iV7J5Egpebc7ulYvxVbMgeFskTQGcorffG1cVsZnM6JOI2UQ2v83DkuSJK8YewJrB1veDS057zq2zqXEb4qfGA79grp4AIm7G2ZTLYm68lBKd1eP2KK9ovVcu3iMtu2g0wr8UE1bf9KscdPkZtB3HYlPdJS+4+7I65vm4zXJZ6cv1i3yyp8btWXw0zPwkZydTaHD2QjRsxTrSbJ+fNFZt43HfnBqLqsTQWkU+UFxmWkVL6ve8zEgCXKwzIUJWjOMeTFT85gZoY=
    - secure: 
        ehWQ1c4MRPUeomHUsiCFKGKbtt3YyFtLVSoinLBhcswBuFCwDyfus3jn9PssFnj64E2cwxyCDY6ZbukHpg6GrHTzbb+tfR+c4MHQnqJ3IRlgSt8eQ5DBFDHV3jcJvJvL9jN9nepGVVL6TAC0AMRIirr9xD5xIYa0Y1bmjEg7FGqnmtGybMW4LTVRXo2uMK8AJ2bUurRAS6wtxc7v9TwMRlFBNpr448H/kEUtxFowr/3qG334ON5v+9wwNVMu0f7ieXrmjPx6yGcEw6GFPbk75OIoqxg0zqODkWZBqRppy6nLZf35rs4h9RnJZWyBut9zuVS7JR1ekkkJJx3nLoVNrw5AMpB9mNBJpkr0AcFYway+KUveFpap9oQpQbY61/TntjC44pJhgWiTX9ZxDoDChG12OPz2Y1Mf4DO/Y6smAiGyVQi4u4IOdBLTQIeMnf2YGF5bUvoickgokBa3nZkA7rO5aqZ1l4eK8gsWrVATzGPE4k2oZbTDdMGLFTAe+klFYe6r8zrbvLGqTgO4WxTklkESn9ESHvb/1nLRefJnI51dPAR+nn3l38vcncmbEmLjzxp0seavGW0ABMXgW/GRNtufsMqesXU6rJj2sbDM3V11QU2BIaQzGIka8qRh/Npgvu4EiZXLqgPj8d0pnC3fp3Vn3Ig4leiosczaATVLMxc=
    - secure: 
        BChBEtSrW2B5azq64lw17vipz1Wi16C/pPLIcGpqrv24kN5g7gdGjJztkefHkPwHfSuwZ/CUqc0FMEUnKiwlX0+OedgjCRawKnE/mxOXkOyC7XHwGS93vVFHD6pp9ajXGXVq62fkjWmakLVap9gmDI/xuVkCVrAa8U7gHKpRy2xbCdkhMGsYBA6J24Yq4wxarLpltyg38l/Nmrp1fVNJwiMtRzkf6vglTxebI0HySnvJJqENK2QSFl8h1nIBQrZTR28GYICZuEAvRrRZt0BbB4MaaysvGJJNdn5FD+ielzvgj7BzsOjOCcEcBfrE+Rqms/1KsCJD1r+qWQ82irR5WHJBaNL+P5L7JEKrKnTeR/JmHf+Fu7riwvUEoGfQeX1szOD6iONvu+6Z3MYiJ8ID6eaorR+PEerd4nYmHJfBC6HZJWEHj+Ztr5RFsFZTG4kJRHyVZgPIZN47w8IXy4rZsVO9BUEpDtCqaH+qvvjVua09+8zxC6H7NvuPAvqKOPzu1YTVYuf34SYS/VzY+WHUvgL2oQ/zGRhKKNzdxttsN0phyVR2xyrOaW/Eh9l4UhWIl7PyE82lgGs/03Y0j8o3zbH5r97CjFLYPYpn17DJKh1mxyUMRG4hdXoE0hMCVdVNj7nniil3YAz12+4jAiLDqlDp6fyh64IJYgiKF4fMv3A=
    - secure: 
        koBRwpngUXvZB1zj7VV72i4DVXJBzgAdWXAyTEAvHpn9Zfk9ddyvu+xeIrevr/0wan6bGxpuPCEfZnkSnGejmjANA6I+dvU98FIBLxrY6okgpIzhYltj9y2e0NhxkjulaQPzlrz0mBtzFdSj1rbvaY4cMdCh+IQsOmmoCdE2GgrNmV5/V21XWY3m8azQuBC9Q8RmTafsKbNahdlYFLrVMz7W2eWWHoDysgPElvWqlXKmeKhDBJOU/aNy4vciNsSEU66TeWKWbl3Wvea+OPgpMr7JvoGWiOohJe9PiOAp0YU3Kv68j8V6Sugh+wSplqjVeKd855w8Yo5gh7FjRiX9MwPidAa+3XmW4sLVCOcRyAknvy9IGjTxb7HdKLMNj/wbdyYIWKGP+ZwM7tIxCY7FlXWIL1crRhMU38ph+gwJs2ws40jkXXBqdqTUicrhtD44PwOi5lWbGHf2EPF7abjOJKMo6TgPP+lnSMQeYolQM+p1vplySfezJ/sisp7fhXMThjgxV6VTZIFRw4ZX6g0K/5Z+v5WY041njAMe5Qits/r3ND10tp47du9M1/rLbFKAuCqtODrQXaeuOJIFCCtYSY8koEpdaIAbSoqct+DsRGylNPiDEzt/g3QgCfT/UGk+CbOxGrEWWVll+j/clwnLFA9TqSjXqmlJWnpAHGiwffY=
    - secure: 
        qAuvv+B97btv5hwN7+M2rrkl3LhSTt2SKwMXjCZalpa2Fxf6inzK4xWYWFacjsamjVgE0u7fovpfwLXHx90axZL5Wi5iODqJlaKECwPnVzHf2G8dNgKoz8jAoULMUxpY/HgP9aKZAj0DTlJQVYGOtYwJX0bUZLwV80+X2REAIGSdr5d7DpMc+M65Zl7hRslrFUYt2vUu/1DGJp/GEDL0DkPcU6ypCY5SS9Hgqg2azCt5v3pnSn0mYC3vzxatagoPq5UNHAVwwzinMVbNCv08Kk0HICicHgLE+iwhNvf2ybNCgFZB9qiehA+0H5fzU+0FiDXSDe4ihgodevOyF557kspDjKHD6bWibsggkg+MubBuoF4C5b13sMZVE4D8ryOLwtPsZx5nZwfIhHh0BnDepXGEFsNuax4+2LcyVxq9LQk5r4FflBpHkHRCfpkxVHnzUKNCd2cJjeZoEIBJPPkrJ6Fct32P+W3aM5ZCNe/QSrl/svY9GbQCPh8bOvbjI8RQA4m4zZzlZVSirRzve9DysiC4KnHEiJkdDmChohykFXG+27q0IVZSg4aKu4NO3+NRfPgeGmBZPIod/qnBS2XRFBAvUaNV+vCQNZlMVrqur+VBFz9OVu8aPTvYpxGbRUg8tSrkTkWuYoF8v5ATDuZsG1kSiMFV7ZoTKfMurk7snes=
    - secure: 
        X40ZWRlfpXoZLlvwiW5n6/LWfI18BnKW/IH+0Dz6f1xGCbc9p/wYSUDdKIeDBUysZmuEu+U19S2a360Sqpms0pNb8ppPn6L6uZv9KmPPxR0T+OHnnuM3ni2U5peCIBuVluoHmgUXmJLNwnqeUaru6YDXL6jH6VTmg+93eY9cOHAwu8byiggahKObK1fj/y3OoN7Oo6wDJLeSrA3Wsxn8NMOq2orD28LupWnKn4S7Y+I6I5A0dWeUO29u3KkOUB/jVc0WjHAcax7I2qjtMjgBoL2gLkJDgeYWaXZlSvD5tn1gCZtF/Scn4k2ErRY8kp0Vnj5+F0AfnHXYLQA296xBeQFPUBXRbiL6PL1RXEDLazh+MvbRi72001+7ouQEV5NY9cnMJan7uBKbV0pxoDgZ6JkGJZVGeJN28T7tP3vyGHoom1EcBya66rqA0yA/M7BHln/ZKh5byjyu+0PfA5Jdh3w3RI0623mLfr+3mKAYx4XY5NRKLvmLsvlhLrRa773a6fdPJmgU8ju80qzMqHDKw/63+ZlzTAHUFuNkexEofraeB4x6jrujfo+ZgH98h1NlCp0DXKokCZPpf4nTM7vIN7OaZa/5SV7L5Eu7AeyORePES9N2sofvgWlK4V1d5YoEzphJd3FymJElyRUjsVFbbuyE0Yn30rw2tmp57h1Mumw=
    - secure: 
        GRldSn7KhI5phBZX31xgdDjXibnXwbUQvvrm6HEjpTdRhoFKsV8XZLyOxF0fAP9YYKaH3PBhPsP6/gz8cWOM7756xpskH7utI+TLGUiduS5jeFf7OiLYWV2IHq4ZwXkNxYc9hgSyCJNFZdCG167YRaGRlqAdgb+k5t2swcHUQg7YXiQLIG1RnNv+Cpn6rZUJMibwPPpJ3uRIpn4NXFtgRyT1Ta/9OhJJ8T/N7hnD6z7RYXySrlqz/ks737tZi8QeGn8Api0GYG5Pu7uo+kiEwUZVpzuaqspEOxScJYfvPKMxo931o4jEcIDytzJFYLrFVmVdDkCk/ykD0DtS6fnJqyzfERo/A1HWMVeh9gq1wsw/rYLcK306Hl4Be58jgNwdzCYNCWZhvZ3tSjZwWJKBlFmozqZroO4uuLQYcxOhTqm6XrpvtBjMIQpuSTkenCob+vUvNgi3XpRm/QbL85S/pj58yoA0kuah8F1WSDwNZDCvB2xY4RqMX5+58EUh77tzDklZynxYu9/Uh8IWsrk0lz7gHdaDY9dtLrpf9YPwd0Lmo/sjJCuT803GBDU3gwqZTWcII6vjJ3DUpFIRgjsSFpo6BsZ8L2CKfRBAM6Xhh2a5l6LJ0nea+IHygxhF4KMH+uwdFQbBDHdxn01r0hMYzq9PafLUCVNSzXvtrFwoojU=
notifications:
  slack:
    secure: 
      LBsSQVYQzd05l9LDijCCEHIAtyJyaTR3KnQEXGKdr66A/6Z9HYV+ZoUA2j4PZEZuvEFx2A2pEipcxVmKx01e8E5mm7iU/49byTPP5y4QRoqpP/1T7y0LZ9ajnlHT4hhp0b0kHC8RlyMtRNbGG8EUmV48sGlSCb7UWSBF0ydqm0isVrvFUdCOBVy741/RWka0EKeCLVUEnUXBQVGvdWybeTN8WcgfuNb/P/lZLIXcK08bLjf1ZgKVrwLgvOTgFxdTe5sJkl8NBQpAf7zm2H11MUfhaI3INn0bTAD1wtRhIg6U0peHfE7UvBd64S/qEgRh5FG9D+3jN04peGJMtKG0tMVRB0VzQNSWJjCKc9+DW2VlolRE7I6VMqLvgte/hP3J6agIjP25+9KQusoNBDCK3RysfuVJKt8FuFq10HsorpxJ327B1GHqOneIxpJbmNVrJuhgevzxf4QDTVEHOI03JCnTQR06HJb31IMWBiNDorKE793PQ+8AIbGJhcn/zq70QYVjgmeU4npmCaLPU32M6asPkea0Uhh61mdygu41hPgp1hv3IEO8TH9plNpb/W4dEXSutO5v624U9FHQ8cGEDhRy7IrPPrZ9cPDYNCNgWcoY+DJYdErpnTxuSL6QOatouZ657ZdeCT11ZgLXcz4oGcuZkZrJ9OnxpryFytrsarc=
