<?php

/**
 * @file
 * AdTechMedia advertising module.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\adtechmedia\AtmClient;

/**
 * Implements hook_theme().
 */
function adtechmedia_theme($existing, $type, $theme, $path) {
  return array(
    'atm_modal' => [
      'variables' => [],
    ],
  );
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function adtechmedia_field_formatter_info_alter(array &$info) {
  $info['text_default']['class'] = 'Drupal\adtechmedia\Plugin\Field\FieldFormatter\AtmTextDefaultFormatter';
  $info['text_trimmed']['class'] = 'Drupal\adtechmedia\Plugin\Field\FieldFormatter\AtmTextTrimmedFormatter';
  $info['text_summary_or_trimmed']['class'] = 'Drupal\adtechmedia\Plugin\Field\FieldFormatter\AtmTextSummaryOrTrimmedFormatter';
}

/**
 * Implements hook_css_alter().
 */
function adtechmedia_css_alter(&$css, AttachedAssetsInterface $assets) {
  // Modify weight to load module css after admin theme.
  if (isset($css['modules/adtechmedia/css/materialdesignicons.css'])
    &&  isset($css['modules/adtechmedia/css/main.css'])) {
    $css['modules/adtechmedia/css/materialdesignicons.css']['weight'] = 300;
    $css['modules/adtechmedia/css/materialdesignicons.css']['group'] = 100;
    $css['modules/adtechmedia/css/main.css']['weight'] = 300;
    $css['modules/adtechmedia/css/main.css']['group'] = 100;
  }
}

/**
 * Implements hook_library_info_alter().
 */
function adtechmedia_library_info_alter(&$libraries, $extension) {
  if ($extension != 'adtechmedia' || !\Drupal::config('adtechmedia.settings')->get('use_atm')) {
    return;
  }

  // Inject dynamically generated ATM js.
  $client = new AtmClient();
  $property = $client->retrieveAtmProperty();

  if (isset($property['BuildPath'])) {
    $settings = reset($libraries['adtechmedia.atmjs']['js']);
    $libraries['adtechmedia.atmjs']['js'] = [
      $property['BuildPath'] => $settings,
    ];
  }
}
