<?php

/**
 * @file
 * AdTechMedia advertising module.
 */

use Drupal\atm\Helper\AtmApiHelper;

/**
 * Implements hook_preprocess_HOOK().
 */
function atm_preprocess_html(&$variables) {
  $variables['page_top']['atm'] = [
    '#markup' => '<div id="atm-modal-content"></div>',
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function atm_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'full') {
    $variables['attributes']['class'][] = 'atm--node--view-mode--full';
  }
}

/**
 * Implements hook_theme().
 */
function atm_theme($existing, $type, $theme, $path) {
  $items = [];

  $items['atm-admin-config-page'] = [
    'variables' => [
      'content_type_select' => NULL,
      'general_configuration' => NULL,
      'content_configuration' => NULL,
      'templates_management' => NULL,
    ],
    'template' => 'admin/config-page',
    'path' => $path . '/templates',
    'preprocess functions' => [
      'atm_admin_config_page_preprocess',
    ],
  ];

  $items['atm-pledge-template-preview'] = [
    'template' => 'admin/atm-pledge-template-preview',
    'path' => $path . '/templates',
    'render element' => 'elements',
  ];

  $items['atm-pay-template-preview'] = [
    'template' => 'admin/atm-pay-template-preview',
    'path' => $path . '/templates',
    'render element' => 'elements',
  ];

  $items['atm-refund-template-preview'] = [
    'template' => 'admin/atm-refund-template-preview',
    'path' => $path . '/templates',
    'render element' => 'elements',
  ];

  $items['atm-unlock-view-template-preview'] = [
    'template' => 'admin/atm-unlock-view-template-preview',
    'path' => $path . '/templates',
    'render element' => 'elements',
  ];

  $items['atm-price-view-template-preview'] = [
    'template' => 'admin/atm-price-view-template-preview',
    'path' => $path . '/templates',
    'render element' => 'elements',
  ];

  return $items;
}

/**
 * Attach atm/js in page.
 */
function atm_page_attachments(array &$attachments) {
  /** @var AtmApiHelper $helper */
  $helper = \Drupal::service('atm.helper');

  $routName = \Drupal::routeMatch()->getRouteName();

  if ($routName == 'atm.config.page') {
    $attachments['#attached']['library'][] = 'atm/api.admin';
  }

  if ($routName == 'atm.config.page' || $routName == 'entity.node.canonical') {
    /** @var \Drupal\node\Entity\Node $node */
    $node = \Drupal::routeMatch()->getParameter('node');

    if ($routName == 'atm.config.page' || in_array($node->getType(), $helper->getSelectedContentTypes())) {
      $atmApi = $helper->get('build_path') . '?' . microtime();

      $https = &$_SERVER['HTTPS'];

      if ($https == 'on') {
        $atmApi = preg_replace("/^http/", 'https', $atmApi);
      }

      $script = "
        (function() {
      
          window.addEventListener('load', function() {
            var body = document.getElementsByTagName('body')[0];
            var js = document.createElement('script');
            js.setAttribute('type', 'text/javascript');
            js.setAttribute('src', '$atmApi');
            js.setAttribute('id', 'atm-js')
            body.appendChild(js);
          })
          
        })()
      ";

      $attachments['#attached']['html_head'][] = [
        [
          '#tag' => 'script',
          '#value' => "window.ATM_SERVICE_WORKER = '/sw-min-js'",
        ],
        'sw',
      ];

      $attachments['#attached']['html_head'][] = [
        [
          '#tag' => 'script',
          '#value' => $script,
        ],
        'atm',
      ];
    }
  }
}

/**
 * Preprocess for config-page.html.twig.
 */
function atm_admin_config_page_preprocess(&$variables) {
  $variables['module_dir'] = drupal_get_path('module', 'atm');
}

/**
 * Implements hook_install().
 */
function atm_install() {
  $timeLimit = ini_get('max_execution_time');
  set_time_limit(0);

  /** @var AtmApiHelper $helper */

  $helper = \Drupal::service('atm.helper');

  $helper->generateApiKey();
  $helper->getAtmHttpClient()->propertyCreate();

  $isThemeRetrieved = $helper->getAtmHttpClient()->retrieveThemeConfig();
  if ($isThemeRetrieved !== TRUE) {
    $helper->createThemeConfig();
  }

  set_time_limit($timeLimit);
}