<?php

/**
 * @file
 * AdTechMedia advertising module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function atm_preprocess_html(&$variables) {
  $variables['page_top']['atm'] = [
    '#markup' => '<div id="atm-modal-content"></div>',
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function atm_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'full') {
    $variables['attributes']['class'][] = 'atm--node--view-mode--full';
  }
}

/**
 * Implements hook_theme().
 */
function atm_theme($existing, $type, $theme, $path) {
  $items = [];

  $items['atm-admin-config-page'] = [
    'variables' => [
      'config_form' => NULL,
      'api_key_info_form' => NULL,
      'overall_position_and_styling' => NULL,
      'content_configuration' => NULL,
      'content_templates' => NULL,
      'general_configuration' => NULL,
      'templates_management' => NULL,
    ],
    'template' => 'admin/config-page',
    'path' => $path . '/templates',
    'preprocess functions' => [
      'atm_admin_config_page_preprocess',
    ],
  ];

  $items['atm-pledge-template-preview'] = [
    'template' => 'admin/atm-pledge-template-preview',
    'path' => $path . '/templates',
    'render element' => 'elements',
  ];

  $items['atm-pay-template-preview'] = [
    'template' => 'admin/atm-pay-template-preview',
    'path' => $path . '/templates',
    'render element' => 'elements',
  ];

  $items['atm-refund-template-preview'] = [
    'template' => 'admin/atm-refund-template-preview',
    'path' => $path . '/templates',
    'render element' => 'elements',
  ];

  return $items;
}

/**
 * Attach atm/js in page.
 */
function atm_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'atm/api';
}

/**
 * Implements hook_ajax_render_alter().
 */
function atm_ajax_render_alter(array &$data) {

}

function atm_admin_config_page_preprocess(&$variables) {
  $variables['module_dir'] = drupal_get_path('module', 'atm');
}
