atm.source.styles.target-cb.*:
  type: config_entity
  label: 'Overall position and styling per theme'
  mapping:
    sticky:
      type: string
      label: 'Sticky'
    width:
      type: string
      label: 'Width'
    offset-top:
      type: string
      label: 'Offset Top'
    offset-left:
      type: string
      label: 'Offset Left'
    scrolling-offset-top:
      type: string
      label: 'Scrolling Offset Top'
    background-color:
      type: string
      label: 'Background Color'
    border:
      type: strint
      label: 'Border'
    font-family:
      type: string
      label: 'Font Family'
    box-shadow:
      type: string
      label: 'Box Shadow'
    footer-background-color:
      type: string
      label: 'Footer Background Color'
    footer-border:
      type: string
      label: 'Footer Border'
    theme-config-id:
      type: string
      label: 'ATM api Theme config ID'
    property-id:
      type: string
      label: 'Property ID'
