sudo: required
dist: trusty
group: edge

language: php

php:
  - 5.6
  - 7.1

cache:
  edge: true
  directories:
    - $HOME/.composer/cache
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin

before_install:
  - sudo rm -rf ~/.nvm
  - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - cp bin/test/package.json .

install:
  - composer install
  - npm install

script:
  - composer test
  - npm test

env:
  global:
  # Node version
  - NODE_RELEASE=7.x
  # To enable run full CI build for specified branches
  - MAJOR_VERSIONS=master,stage
  # Disable interactive user mode ###
  - DEEP_NO_INTERACTION=1
  # Set type of E2E tests. Public, private or none
  - E2E_TESTING=none
  # S3_BUCKET_NAME=[secured]
  - secure: NIHVj4RBAHpPyLFXfZX6Cvo0xhF8b2cXEY10P/++w0Zc4P2QPX3i6jMCoP87beIBKerawB3hfb+6tM7/23eNjfYCkW3IBEnpSo3KhyZYSRM8JUmkOMB589/MeNfJQqLAJlUZ/NP/91yzRcNxOBB0dMBj5bU0XklmKBxEt9jeAhbq67HHI4pq653ms4fzOW0P4tRQcASKgRCB2zO4Vr5fBPHHmXdgd7KI/pEs1v1JhZbIAoiT3aoMzD4j8z5gKlCYASvsT2omT5kauxCGToYFb0nKZVsYsdchZvMWvLcry1ttfYIXsF0jrKnoqcWfSTShTppuudaq3Mx3hzYhUgeXGPlD1/+DXdtv23Vs68+QuBtqjfCgXVRKhvVVX4p8NprtFkU00tRrglktwnBf9j9k74SNKsrMeRNx8iV7J5Egpebc7ulYvxVbMgeFskTQGcorffG1cVsZnM6JOI2UQ2v83DkuSJK8YewJrB1veDS057zq2zqXEb4qfGA79grp4AIm7G2ZTLYm68lBKd1eP2KK9ovVcu3iMtu2g0wr8UE1bf9KscdPkZtB3HYlPdJS+4+7I65vm4zXJZ6cv1i3yyp8btWXw0zPwkZydTaHD2QjRsxTrSbJ+fNFZt43HfnBqLqsTQWkU+UFxmWkVL6ve8zEgCXKwzIUJWjOMeTFT85gZoY=
  # AWS_DEFAULT_REGION=[secured]
  - secure: ehWQ1c4MRPUeomHUsiCFKGKbtt3YyFtLVSoinLBhcswBuFCwDyfus3jn9PssFnj64E2cwxyCDY6ZbukHpg6GrHTzbb+tfR+c4MHQnqJ3IRlgSt8eQ5DBFDHV3jcJvJvL9jN9nepGVVL6TAC0AMRIirr9xD5xIYa0Y1bmjEg7FGqnmtGybMW4LTVRXo2uMK8AJ2bUurRAS6wtxc7v9TwMRlFBNpr448H/kEUtxFowr/3qG334ON5v+9wwNVMu0f7ieXrmjPx6yGcEw6GFPbk75OIoqxg0zqODkWZBqRppy6nLZf35rs4h9RnJZWyBut9zuVS7JR1ekkkJJx3nLoVNrw5AMpB9mNBJpkr0AcFYway+KUveFpap9oQpQbY61/TntjC44pJhgWiTX9ZxDoDChG12OPz2Y1Mf4DO/Y6smAiGyVQi4u4IOdBLTQIeMnf2YGF5bUvoickgokBa3nZkA7rO5aqZ1l4eK8gsWrVATzGPE4k2oZbTDdMGLFTAe+klFYe6r8zrbvLGqTgO4WxTklkESn9ESHvb/1nLRefJnI51dPAR+nn3l38vcncmbEmLjzxp0seavGW0ABMXgW/GRNtufsMqesXU6rJj2sbDM3V11QU2BIaQzGIka8qRh/Npgvu4EiZXLqgPj8d0pnC3fp3Vn3Ig4leiosczaATVLMxc=
  # AWS_ACCESS_KEY_ID=[secured]
  - secure: Gd4IDEyMx6Og+V/JDywXKD9zZUdf7OtiuUtEB0r8akMRtTPn+LXd07dj4laAKGb278n3lA0TJ5kSLwLdlBToxLAZ7k806jEV/3BzImbY7DIY54B4NyL4pvveE8BPU7BOh7oXwA7i+rYgCEnoYzBkx/1uGdiN4k9VOaBofe8p1orIQx37kLSVYQjNci409FOS2RbnIg1kLSnq++4EZBB9oqMgau4dgnOBJseiznqKABzTGriwGZY8T0WBlftLdbV7CH0LUqg0VLL7mKE/uYSAVpkR6ATdJgQEkH5HNUyLl5HKrol2OQ2sSfo6xDxUTO4pQrRyXnVUzhNwOHV4JZrZF7GlAFvksQosO3zWmWVUmTDt1Z4mJOHqN6GYfma3Bx+nQp80TJFMxJmUWT6qX2ogs1TsQkryllz0GbYE9PkAstG8ynJS318jjLAmVgmaS0aU2Wu6yAWLsG9bGGT6MGsxw6hYjzWqDZNVr+7kjIYeZn+GNEUMHj4NUQRSS8+2a7Rmr7DUThs1MKkMoMBs2Pho87+Ti2D+UJBBINsKlKrcc+DO2hx7NxpUMQveAoikLE+HjUM4WI/8wiXZy4Fg9IgiaH3eL6oB+gIzqdGaBmRaEMyrq1Vyl3S3NXms5nNLwVRtG/eHqZg9nlyI3U1ykcSO/jv5Kaz9/QKopDjGEjy0MAk=
  # AWS_SECRET_ACCESS_KEY=[secured]
  - secure: buVPfzvEg510EtsvQUFNy7Wmk6swwSmvPjX1dof/tJg69jtSfLxPT3uyeDyfMuiT+lkkS3t97ZNdBWdbpHV6kBZVEtT93dnvPp5YWZNHxObw8wQzqlNVLeoASG9V1PjzQNlSD6FGblZTl+Z+q5ben2tm1KMvyeXppMu4Nc9neg+w1unsP3fqA4Xpk9N/FjdaVTwRhvzU6ZRVtvArPrLiomOS7DFclqMOe7adhKJ45kQLSX2cMChysp9x63Qwe2w0pdUYvKO62FablrXT7PxJGyB28EZi+4mnNCW92ecSrCmzGHaiPkrl7WnQ0EHtOYA6wxJaJzHlMYTx+/CCokSUxXQbOlzC/ZIW1Xp3sv2mTYDGZsiihX52CcIxb2qogHkTTPj66IiBiT4pGC6wWZnHKDzjD7TQEfx8eeK3efPw4e4ExaRLAQf7ovAFFKAUvdAJmAqSXdSSnlsdo1FVtrpiSIeGxPOMcTli8aLr90chu+IELsD22+495zhjy6nzc0i0S5ahBvAUucymYkzARL+HL5THjFG3VaUtipTQrtSNVKbHmPpJ2LHfqLHCQmt9Pu2hLzaUMzhvysrKdyduHn1XLQWfCMs9bhMgHHlRrO1YCpDKcxTGNpAJBIU/e28OVGDq34Y7VPSK+P4eP6gUlJSmBO8+qcvdaPErMdvmxzn29GI=
  # GITHUB_OAUTH_TOKEN=[secured]
  - secure: qAuvv+B97btv5hwN7+M2rrkl3LhSTt2SKwMXjCZalpa2Fxf6inzK4xWYWFacjsamjVgE0u7fovpfwLXHx90axZL5Wi5iODqJlaKECwPnVzHf2G8dNgKoz8jAoULMUxpY/HgP9aKZAj0DTlJQVYGOtYwJX0bUZLwV80+X2REAIGSdr5d7DpMc+M65Zl7hRslrFUYt2vUu/1DGJp/GEDL0DkPcU6ypCY5SS9Hgqg2azCt5v3pnSn0mYC3vzxatagoPq5UNHAVwwzinMVbNCv08Kk0HICicHgLE+iwhNvf2ybNCgFZB9qiehA+0H5fzU+0FiDXSDe4ihgodevOyF557kspDjKHD6bWibsggkg+MubBuoF4C5b13sMZVE4D8ryOLwtPsZx5nZwfIhHh0BnDepXGEFsNuax4+2LcyVxq9LQk5r4FflBpHkHRCfpkxVHnzUKNCd2cJjeZoEIBJPPkrJ6Fct32P+W3aM5ZCNe/QSrl/svY9GbQCPh8bOvbjI8RQA4m4zZzlZVSirRzve9DysiC4KnHEiJkdDmChohykFXG+27q0IVZSg4aKu4NO3+NRfPgeGmBZPIod/qnBS2XRFBAvUaNV+vCQNZlMVrqur+VBFz9OVu8aPTvYpxGbRUg8tSrkTkWuYoF8v5ATDuZsG1kSiMFV7ZoTKfMurk7snes=
  # CODECLIMATE_REPO_TOKEN_MASTER=[secured]
  - secure: X40ZWRlfpXoZLlvwiW5n6/LWfI18BnKW/IH+0Dz6f1xGCbc9p/wYSUDdKIeDBUysZmuEu+U19S2a360Sqpms0pNb8ppPn6L6uZv9KmPPxR0T+OHnnuM3ni2U5peCIBuVluoHmgUXmJLNwnqeUaru6YDXL6jH6VTmg+93eY9cOHAwu8byiggahKObK1fj/y3OoN7Oo6wDJLeSrA3Wsxn8NMOq2orD28LupWnKn4S7Y+I6I5A0dWeUO29u3KkOUB/jVc0WjHAcax7I2qjtMjgBoL2gLkJDgeYWaXZlSvD5tn1gCZtF/Scn4k2ErRY8kp0Vnj5+F0AfnHXYLQA296xBeQFPUBXRbiL6PL1RXEDLazh+MvbRi72001+7ouQEV5NY9cnMJan7uBKbV0pxoDgZ6JkGJZVGeJN28T7tP3vyGHoom1EcBya66rqA0yA/M7BHln/ZKh5byjyu+0PfA5Jdh3w3RI0623mLfr+3mKAYx4XY5NRKLvmLsvlhLrRa773a6fdPJmgU8ju80qzMqHDKw/63+ZlzTAHUFuNkexEofraeB4x6jrujfo+ZgH98h1NlCp0DXKokCZPpf4nTM7vIN7OaZa/5SV7L5Eu7AeyORePES9N2sofvgWlK4V1d5YoEzphJd3FymJElyRUjsVFbbuyE0Yn30rw2tmp57h1Mumw=
  # CODECLIMATE_REPO_TOKEN_DEV=[secured]
  - secure: GRldSn7KhI5phBZX31xgdDjXibnXwbUQvvrm6HEjpTdRhoFKsV8XZLyOxF0fAP9YYKaH3PBhPsP6/gz8cWOM7756xpskH7utI+TLGUiduS5jeFf7OiLYWV2IHq4ZwXkNxYc9hgSyCJNFZdCG167YRaGRlqAdgb+k5t2swcHUQg7YXiQLIG1RnNv+Cpn6rZUJMibwPPpJ3uRIpn4NXFtgRyT1Ta/9OhJJ8T/N7hnD6z7RYXySrlqz/ks737tZi8QeGn8Api0GYG5Pu7uo+kiEwUZVpzuaqspEOxScJYfvPKMxo931o4jEcIDytzJFYLrFVmVdDkCk/ykD0DtS6fnJqyzfERo/A1HWMVeh9gq1wsw/rYLcK306Hl4Be58jgNwdzCYNCWZhvZ3tSjZwWJKBlFmozqZroO4uuLQYcxOhTqm6XrpvtBjMIQpuSTkenCob+vUvNgi3XpRm/QbL85S/pj58yoA0kuah8F1WSDwNZDCvB2xY4RqMX5+58EUh77tzDklZynxYu9/Uh8IWsrk0lz7gHdaDY9dtLrpf9YPwd0Lmo/sjJCuT803GBDU3gwqZTWcII6vjJ3DUpFIRgjsSFpo6BsZ8L2CKfRBAM6Xhh2a5l6LJ0nea+IHygxhF4KMH+uwdFQbBDHdxn01r0hMYzq9PafLUCVNSzXvtrFwoojU=

notifications:
  # Send notifications to Slack
  slack:
    secure: LBsSQVYQzd05l9LDijCCEHIAtyJyaTR3KnQEXGKdr66A/6Z9HYV+ZoUA2j4PZEZuvEFx2A2pEipcxVmKx01e8E5mm7iU/49byTPP5y4QRoqpP/1T7y0LZ9ajnlHT4hhp0b0kHC8RlyMtRNbGG8EUmV48sGlSCb7UWSBF0ydqm0isVrvFUdCOBVy741/RWka0EKeCLVUEnUXBQVGvdWybeTN8WcgfuNb/P/lZLIXcK08bLjf1ZgKVrwLgvOTgFxdTe5sJkl8NBQpAf7zm2H11MUfhaI3INn0bTAD1wtRhIg6U0peHfE7UvBd64S/qEgRh5FG9D+3jN04peGJMtKG0tMVRB0VzQNSWJjCKc9+DW2VlolRE7I6VMqLvgte/hP3J6agIjP25+9KQusoNBDCK3RysfuVJKt8FuFq10HsorpxJ327B1GHqOneIxpJbmNVrJuhgevzxf4QDTVEHOI03JCnTQR06HJb31IMWBiNDorKE793PQ+8AIbGJhcn/zq70QYVjgmeU4npmCaLPU32M6asPkea0Uhh61mdygu41hPgp1hv3IEO8TH9plNpb/W4dEXSutO5v624U9FHQ8cGEDhRy7IrPPrZ9cPDYNCNgWcoY+DJYdErpnTxuSL6QOatouZ657ZdeCT11ZgLXcz4oGcuZkZrJ9OnxpryFytrsarc=
